"""Renamed publish_date to published_date in Book model.

Revision ID: d97f4561ab8a
Revises: 
Create Date: 2024-12-09 18:14:23.017272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97f4561ab8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_date', sa.String(length=10), nullable=True))
        batch_op.drop_column('publish_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish_date', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('published_date')

    # ### end Alembic commands ###
